import { ObjectId, OptionalId } from "mongodb";

/** Project JSON Schema generated by Gemini */
export type ProjectGenerated = {
  projectName: string;
  projectDescription: string;
  boardName: string; // Board name or boardId?
  boardDescription: string;
  tasks: Array<{
    title: string;
    description: string;
    priority: "low" | "medium" | "high";
    tags: string[];
  }>
};

export type Project = OptionalId<{
  name: string;
  description: string;
  slug: string;
  boardName: string; // Board name or boardId?
  createdAt: Date;
  createdBy: ObjectId;
  lastModifiedAt: Date;
  tasks: ObjectId[];
}>