import { ObjectId, OptionalId } from "mongodb";
import { Task } from "./task.types";


/** Project JSON Schema generated by Gemini */
export type ProjectGenerated = {
  boardName: string; // Board name or boardId?
  projectDescription: string;
  tasks: Array<{
    title: string;
    description: string;
    priority: "low" | "medium" | "high";
    tags: string[];
  }>
};

export type Project = OptionalId<{
  name: string;
  description: string;
  slug: string;
  boardName: string; // Board name or boardId?
  tasks: ObjectId[];
}>